# Identifying special matrices

```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```


#### Objective
* Write a function that will test if a 4×4 matrix is singular,
     * to determine if an inverse exists, before calculating it.
     * Use the method of converting a matrix to echelon form,
     * test if the method fails by leaving zeros that can’t be removed on the leading diagonal.    

In [1]:
import numpy as np

In [12]:
def isSingular(A):
    B = np.array(A, dtype=np.float_) 
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False


# defining error flag. For when things go wrong if the matrix is singular.
class MatrixIsSingular(Exception): pass


def fixRowZero(A):
    if A[0, 0] == 0:
        A[0] = A[0] + A[1]
    if A[0, 0] == 0:
        A[0] = A[0] + A[2]
    if A[0, 0] == 0:
        A[0] = A[0] + A[3]
    if A[0, 0] == 0:
        raise MatrixIsSingular()
    A[0] = A[0] / A[0, 0]
    return A


def fixRowOne(A):
    A[1] = A[1] - A[1, 0] * A[0]
    if A[1, 1] == 0:
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1, 0] * A[0]
    if A[1, 1] == 0:
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1, 0] * A[0]
    if A[1, 1] == 0:
        raise MatrixIsSingular()
    A[1] = A[1] / A[1, 1]
    return A


def fixRowTwo(A):
    A[2] = A[2] - A[2, 0] * A[0]
    A[2] = A[2] - A[2, 1] * A[1]
    # testing that the diagonal element is not zero.
    if A[2, 2] == 0:
        A[2] = A[2] + A[3]
        A[2] = A[2] - A[2, 0] * A[0]
        A[2] = A[2] - A[2, 1] * A[1]
    if A[2, 2] == 0:
        raise MatrixIsSingular()
    # setting the diagonal element to one
    A[2] = A[2] / A[2, 2]
    return A


def fixRowThree(A):
    # setting the sub-diagonal elements of row three to zero.
    A[3] = A[3] - A[3, 0] * A[0]
    A[3] = A[3] - A[3, 1] * A[1]
    A[3] = A[3] - A[3, 2] * A[2]
    # testing if the diagonal element is zero.
    if A[3, 3] == 0:
        raise MatrixIsSingular()
    # Transforming the row to set the diagonal element to one.
    A[3] = A[3] / A[3, 3]
    return A

<code> Testing code </code>

In [13]:
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
isSingular(A)

True

In [14]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)
fixRowZero(A)

array([[  1. ,   7.5,  -2.5,   3.5],
       [  2. ,   8. ,   0. ,   4. ],
       [  3. ,  12. ,   0. ,   5. ],
       [  1. ,   3. ,   1. ,   3. ]])

In [15]:
fixRowOne(A)

array([[  1.        ,   7.5       ,  -2.5       ,   3.5       ],
       [ -0.        ,   1.        ,  -0.71428571,   0.42857143],
       [  3.        ,  12.        ,   0.        ,   5.        ],
       [  1.        ,   3.        ,   1.        ,   3.        ]])

In [16]:
fixRowTwo(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [17]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])